services:
  website:
    build: .
    container_name: web-portfolio-v1
    image: portfolio-v1:latest
    ports:
      - "127.0.0.1:4000:3000"
    restart: unless-stopped
    networks:
      - net-portfolio-v1

networks:
  net-portfolio-v1:
    driver: bridge
    name: net-portfolio-v1
